// import './js/js-partials/API';
// import './js/js-partials/appendFilmsMarkup';
// import './js/js-partials/clearFilmsContainer';
import './js/js-partials/teamModal';
import './js/js-partials/renderWatchedList';
import './js/js-partials/renderQueueList';
// import './js/js-partials/openModalFilm';
import './js/js-partials/loader';
import './js/js-partials//onLibraryBtnsClick';
import "./js/js-partials/theme";
import "./js/js-partials/button-up";
import "./js/js-partials/log-out";